services:
  hubdam_share:
    build:
      context: ./
      dockerfile: Dockerfile
    image: hubdam_app_image
    container_name: hubdam_share
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    networks:
      - hubdam_network

  nginx:
    image: nginx:alpine
    container_name: hubdam_share_webserver
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - hubdam_share
    networks:
      - hubdam_network

  mysql:
    image: mysql:latest
    container_name: hubdam_share_db
    restart: unless-stopped
    ports:
      - 3310:3306
    environment:
      # MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${DB_DATABASE}
      # MYSQL_USER: ${DB_USERNAME}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hubdam_share
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes: 
      - dbdata:/var/lib/mysql/
    networks:
      - hubdam_network

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: hubdam_share_phpmyadmin
    restart: unless-stopped
    ports:
      - "8383:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - hubdam_network

volumes:
  dbdata:
    driver: local

networks:
  hubdam_network:
    driver: bridge
