const Ziggy = {
  url: "https:\/\/hubdamdigital.com\/hubdamshare",
  port: null,
  defaults: {},
  routes: {
    "filament.exports.download": {
      uri: "filament\/exports\/{export}\/download",
      methods: ["GET", "HEAD"],
      parameters: ["export"],
      bindings: { export: "id" },
    },
    "filament.imports.failed-rows.download": {
      uri: "filament\/imports\/{import}\/failed-rows\/download",
      methods: ["GET", "HEAD"],
      parameters: ["import"],
      bindings: { import: "id" },
    },
    "filament.admin.auth.login": { uri: "admin\/login", methods: ["GET", "HEAD"] },
    "filament.admin.auth.logout": { uri: "admin\/logout", methods: ["POST"] },
    "filament.admin.auth.profile": { uri: "admin\/profile", methods: ["GET", "HEAD"] },
    "filament.admin.pages.dashboard": { uri: "admin", methods: ["GET", "HEAD"] },
    "filament.admin.resources.page-content.index": { uri: "admin\/page-content", methods: ["GET", "HEAD"] },
    "filament.admin.resources.excel.index": { uri: "admin\/excel", methods: ["GET", "HEAD"] },
    "filament.admin.resources.excel.create": { uri: "admin\/excel\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.excel.edit": {
      uri: "admin\/excel\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "filament.admin.resources.images.index": { uri: "admin\/images", methods: ["GET", "HEAD"] },
    "filament.admin.resources.images.create": { uri: "admin\/images\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.images.edit": {
      uri: "admin\/images\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "filament.admin.resources.pdf.index": { uri: "admin\/pdf", methods: ["GET", "HEAD"] },
    "filament.admin.resources.pdf.create": { uri: "admin\/pdf\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.pdf.edit": {
      uri: "admin\/pdf\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "filament.admin.resources.powerpoint.index": { uri: "admin\/powerpoint", methods: ["GET", "HEAD"] },
    "filament.admin.resources.powerpoint.create": { uri: "admin\/powerpoint\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.powerpoint.edit": {
      uri: "admin\/powerpoint\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "filament.admin.resources.word.index": { uri: "admin\/word", methods: ["GET", "HEAD"] },
    "filament.admin.resources.word.create": { uri: "admin\/word\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.word.edit": {
      uri: "admin\/word\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "filament.admin.resources.admins.index": { uri: "admin\/admins", methods: ["GET", "HEAD"] },
    "filament.admin.resources.admins.create": { uri: "admin\/admins\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.admins.edit": {
      uri: "admin\/admins\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "filament.admin.resources.users.index": { uri: "admin\/users", methods: ["GET", "HEAD"] },
    "filament.admin.resources.users.create": { uri: "admin\/users\/create", methods: ["GET", "HEAD"] },
    "filament.admin.resources.users.edit": {
      uri: "admin\/users\/{record}\/edit",
      methods: ["GET", "HEAD"],
      parameters: ["record"],
    },
    "sanctum.csrf-cookie": { uri: "sanctum\/csrf-cookie", methods: ["GET", "HEAD"] },
    "livewire.update": { uri: "hubdamshare\/livewire\/update", methods: ["POST"] },
    "livewire.upload-file": { uri: "livewire\/upload-file", methods: ["POST"] },
    "livewire.preview-file": {
      uri: "livewire\/preview-file\/{filename}",
      methods: ["GET", "HEAD"],
      parameters: ["filename"],
    },
    beranda: { uri: "\/", methods: ["GET", "HEAD"] },
    berkas: { uri: "berkas", methods: ["GET", "HEAD"] },
    "berkas.create": { uri: "berkas\/create", methods: ["GET", "HEAD"] },
    "berkas.store": { uri: "berkas", methods: ["POST"] },
    "berkas.show": { uri: "berkas\/{berka}", methods: ["GET", "HEAD"], parameters: ["berka"] },
    "berkas.edit": { uri: "berkas\/{berka}\/edit", methods: ["GET", "HEAD"], parameters: ["berka"] },
    "berkas.update": { uri: "berkas\/{berka}", methods: ["PUT", "PATCH"], parameters: ["berka"] },
    "berkas.destroy": { uri: "berkas\/{berka}", methods: ["DELETE"], parameters: ["berka"] },
    "berkas.download": { uri: "berkas\/download\/{id}", methods: ["GET", "HEAD"], parameters: ["id"] },
    staff: { uri: "divisi\/{uri}", methods: ["GET", "HEAD"], parameters: ["uri"] },
    "profile.edit": { uri: "profile", methods: ["GET", "HEAD"] },
    "profile.update": { uri: "profile", methods: ["POST"] },
    login: { uri: "login", methods: ["GET", "HEAD"] },
    logout: { uri: "logout", methods: ["POST"] },
    "storage.local": { uri: "storage\/{path}", methods: ["GET", "HEAD"], wheres: { path: ".*" }, parameters: ["path"] },
  },
};
if (typeof window !== "undefined" && typeof window.Ziggy !== "undefined") {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
