name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hubdam_share_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Copy .env.testing
        run: cp .env.testing.example .env.testing

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install Node dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Generate app key (fallback if not using secrets)
        run: php artisan key:generate --env=testing
        if: ${{ !secrets.APP_KEY }}

      - name: Run Migrations (Testing DB)
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: hubdam_share_test
          DB_USERNAME: root
          DB_PASSWORD: root
          APP_KEY: ${{ secrets.APP_KEY }}
        run: php artisan migrate --env=testing

      - name: Run Laravel Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: hubdam_share_test
          DB_USERNAME: root
          DB_PASSWORD: root
          APP_KEY: ${{ secrets.APP_KEY }}
        run: php artisan test --env=testing
